# Generated by Django 5.1.7 on 2025-03-24 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialFacility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='施設名')),
                ('address', models.TextField(verbose_name='住所')),
                ('latitude', models.FloatField(verbose_name='緯度')),
                ('longitude', models.FloatField(verbose_name='経度')),
                ('access_info', models.TextField(blank=True, null=True, verbose_name='アクセス情報')),
                ('nursing_room', models.BooleanField(default=False, verbose_name='授乳室')),
                ('diaper_changing_room', models.BooleanField(default=False, verbose_name='おむつ替え室')),
                ('stroller', models.BooleanField(default=False, verbose_name='ベビーカー')),
                ('baby_chair', models.BooleanField(default=False, verbose_name='ベビーチェア')),
                ('parking', models.BooleanField(default=False, verbose_name='駐車場')),
                ('kids_discount', models.BooleanField(default=False, verbose_name='お子様割引有無')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='commercial_facility_id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='commercial_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.commercialfacility', verbose_name='商業施設'),
        ),
    ]
