# Generated by Django 5.1.7 on 2025-03-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_commercialfacility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialfacility',
            options={'verbose_name': '商業施設情報', 'verbose_name_plural': '商業施設情報'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'レストラン情報', 'verbose_name_plural': 'レストラン情報'},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='baby_food_allowed',
            field=models.BooleanField(default=False, verbose_name='離乳食持ち込み可'),
        ),
    ]
