# Generated by Django 5.1.7 on 2025-03-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_commercialfacility_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='daycare_facility',
            field=models.BooleanField(default=False, verbose_name='託児施設あり'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='elementary_schoolers_allowed',
            field=models.BooleanField(default=False, verbose_name='小学生可'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='infants_allowed',
            field=models.BooleanField(default=False, verbose_name='乳幼児可'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='play_zone',
            field=models.BooleanField(default=False, verbose_name='プレイゾーンあり'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='preschoolers_allowed',
            field=models.BooleanField(default=False, verbose_name='未就学児可'),
        ),
    ]
