# Generated by Django 5.1.7 on 2025-04-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_restaurant_retty_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='sunken_kotatsu',
            new_name='horigotatsu',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='low_salt',
            field=models.BooleanField(default=False, verbose_name='減塩メニューあり'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='protein_rich',
            field=models.BooleanField(default=False, verbose_name='タンパク質がとれる'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vegetable_like',
            field=models.BooleanField(default=False, verbose_name='野菜が好きになる'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vegetable_rich',
            field=models.BooleanField(default=False, verbose_name='野菜が食べれる'),
        ),
    ]
